---
galaxy_info:
  role_name: mk_livestatus
  namespace: mahadzar81
  author: Mahadzar
  description: Optional MK Livestatus broker module for Nagios Core.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions: ["8", "9", "10"]
    - name: Debian
      versions: ["bullseye", "bookworm", "trixie"]
    - name: Ubuntu
      versions: ["jammy", "noble"]
  galaxy_tags:
    - nagios
    - livestatus
dependencies:
  - role: mahadzar81.nagiosql.common
